name: ed
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - notebook
  - jupyterlab
  - jupytext
  - matplotlib=3.3.2
  - nilearn
  - seaborn=0.11.1
  - pingouin=0.3.9
  - nipype
  - numpy
  - pandas=1.4.1
  - openpyxl
  - twine=3.1.1
  - nibabel
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - nodejs
  - ptitprince
  - pip
  - pip:
    - bctpy
    - wbplot
    - brainsmash
    - brainspace
    - Pillow
    - netneurotools
    - wordcloud
    - joypy==0.2.4
    - rpy2==3.5.4
    - vtk==9.1.0
